<a href="https://colab.research.google.com/github/blesshomes/blesshomes.github.io/blob/master/What_is_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

# 手始め

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[1.1163e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.9227, 0.3514, 0.5696],
        [0.3784, 0.5228, 0.1202],
        [0.2681, 0.6402, 0.9505],
        [0.7573, 0.5865, 0.6637],
        [0.2363, 0.0187, 0.2884]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3]) #pytorchはダイレクトに行列を作れる
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double) #行列xを1で埋める（double型）
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float) #行列xを平均0,分散1の正規分布で埋める。型の変換も同時に行える。
print(x)

tensor([[-0.2996, -1.1762, -0.4174],
        [-0.0438,  0.8004, -0.7810],
        [ 0.2450, -0.1718,  1.4304],
        [ 0.6248, -1.5019, -1.0005],
        [-2.3013, -0.6940,  0.0817]])


In [16]:
print(x.size()) #.sizeでサイズが求まる

torch.Size([5, 3])


In [17]:
y = torch.rand(5, 3)
print(x+y) #"+"で加算

tensor([[ 0.3052, -1.0776, -0.3033],
        [ 0.2580,  0.8498,  0.1163],
        [ 0.8517, -0.0884,  1.8198],
        [ 1.3014, -0.6735, -0.8348],
        [-1.9255, -0.0579,  1.0026]])


In [18]:
print(torch.add(x,y)) #torch.add()でも加算が計算可能

tensor([[ 0.3052, -1.0776, -0.3033],
        [ 0.2580,  0.8498,  0.1163],
        [ 0.8517, -0.0884,  1.8198],
        [ 1.3014, -0.6735, -0.8348],
        [-1.9255, -0.0579,  1.0026]])


In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result) #引数にout=を持ってくると結果を代入できる
print(result)

tensor([[ 0.3052, -1.0776, -0.3033],
        [ 0.2580,  0.8498,  0.1163],
        [ 0.8517, -0.0884,  1.8198],
        [ 1.3014, -0.6735, -0.8348],
        [-1.9255, -0.0579,  1.0026]])


In [21]:
y.add_(x) #後から数値を加算させたい時に有効か
print(y)

tensor([[ 0.3052, -1.0776, -0.3033],
        [ 0.2580,  0.8498,  0.1163],
        [ 0.8517, -0.0884,  1.8198],
        [ 1.3014, -0.6735, -0.8348],
        [-1.9255, -0.0579,  1.0026]])


In [22]:
print(x[:, 1]) #indexの取り扱いはnumpyと同様！

tensor([-1.1762,  0.8004, -0.1718, -1.5019, -0.6940])


In [23]:
x = torch.randn(4, 4)
y = x.view(16) #.viewでreshapeすることができる
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
x = torch.randn(1) 
print(x)
print(x.item())　#たった一個の数字なら.itemで数値を抜き取れる

tensor([-0.9300])
-0.9300071597099304


# Numpyとのスイッチ

## Torch tensorをNumPy arrayに

In [27]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [28]:
b = a.numpy() #.numpy()とするだけ！！
print(b)

[1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b) #何と変更は自動的に反映される

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## NumPy arrayをTorch tensorに

In [30]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)　#torch.from_numpy()、ととても自然な変換
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors (?)

In [0]:
#どういうこっちゃ

In [0]:
#CUDA環境だとそっちを使う時は環境を変えるコードがあるということか
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)  
    x = x.to(device)                       
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 